version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: miraie-ac-backend
    ports:
      - "5005:5005"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: miraie-ac-frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    depends_on:
      - backend
